modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://gitlab.com/starliteheart/cobbleride/-/issues"

[[mods]]
modId = "cobbleride"
version = "${mod_version}"
displayName = "Cobblemon: Ride On!"
authors = "StarliteHeart"
description = '''
Ride astride your Pokemon companions, as you travel by land, air or sea together!
'''

[[mixins]]
config = "cobbleride-common.mixins.json"

[[dependencies.cobbleride]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobbleride]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobbleride]]
modId = "cobblemon"
mandatory = true
versionRange = "[${cobblemon_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobbleride]]
modId = "petyourcobblemon"
type = "optional"
versionRange = "[1.3.3,)"
ordering = "NONE"
side = "BOTH"
